#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          shutdown_monitor
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts or stops the daemon watching the power switch
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.  This example start a
#                    single forking daemon capable of writing a pid
#                    file.  To get other behavoirs, implemend
#                    do_start(), do_stop() or other functions to
#                    override the defaults in /lib/init/init-d-script.
### END INIT INFO

# Author: David Slama <dslam127@gmail.com>
# Date: 7 November 2015

DESC="Shutdown Switch Monitor"
DAEMON=/usr/local/sbin/shutdown_daemon
NAME=shutdown_daemon

case $1 in
    start)
        $DAEMON &
    ;;
    stop)
        pkill $NAME
    ;;
    restart)
        $0 stop
        sleep 2
        $0 start
    ;;
    *)
        echo "arguments: start, stop, and restart"
    ;;
esac