#!/bin/bash

# shell script to control the blue function led

case $1 in
    on)
        echo 1 > /sys/class/gpio/gpio39/value
    ;;
    off)
        echo 0 > /sys/class/gpio/gpio39/value
    ;;
    state)
        VAL="$(cat /sys/class/gpio/gpio39/value)"
        if [ "$VAL" == "0" ]; then
            echo "off"
        elif [ "$VAL" == "1" ]; then
            echo "on"
        fi
    ;;
    *)
        echo "arguments: on, off, or state"
    ;;
esac